#!/bin/sh
export PATH="/home/jeff/fitz/kde/bin:${PATH}"
export KDEDIRS="/home/jeff/fitz/kde:${KDEDIRS}"
cd /home/jeff/fitz/build
make install
killall kwin
sleep .1
exec kwin --replace
#kcmshell kwindecoration
